#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service btccore stop || echo "btccore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "btccore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "btccore.service" || echo "btccore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so btccore could not be stopped"
fi
